### ISSUE TITLE
 [CheatsBeGone] Task #1769 for CheatsBeGone v1.3 generated an exception

### ISSUE THREAD

**Issue by FuchsPlayZ** [gc2023/CheatsBeGone#107]
# Console Error
 [CheatsBeGone] Task #1769 for CheatsBeGone v1.3 generated an exception
java.lang.AbstractMethodError
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

# When the bug occurrs?
everytime i start/restart/reload the server

# Server Version:
Spigot 1.8.8
# Anticheat Version:
Lastet
# ProtocolLib Version:
Lastet
# Is the config file the newest?: (yes/no)
yes

**Comment by DogsDev** [comment]
Hello,
im not the dev but as far as im awear that looks like protocols problem not the anticheat.

Suggestions: 
try stopping the server and staring it again.
try finding a version of protocol lib that is more stable or a make sure the version is meant for 1.8.8

i hope this helped.
**-ExslodingDogs**

**Comment by FuchsPlayZ** [comment]
Thx 4 u r help i finally fixed it

HLS <notifications@github.com> schrieb am Sa., 10. Aug. 2019, 16:07:

**Comment by gc2023** [comment]
Yes as far as i have tested, this seems to be a bug with ProtocolLib. I am trying to figure out the best way to fix this bug, however it might be sourced in the library its self.
